### ISSUE TITLE
CTOV Wizards compatibility update to 2.1 datapack

### ISSUE THREAD

**Issue by bakardos** [DenisMasterHerobrine/ElerionBloodNSteel#102]
ctov-wizards-compat-1.0.0a contains an incorrect block ID in the NBT structure file, causing it to crash during generation. v2.1 works fine.

ChoiceTheorem/ChoiceTheorem-s-overhauled-village#91

**Comment by ChoiceTheorem** [comment]
Do not use it in 1.20 CTOV at any cost!

**Comment by DenisMasterHerobrine** [comment]
Updated to 2.1 in 0.9.5.1. The pack is on 1.19.2, so it should be ok for now, however, it seems that this was already patched by me since March 12, but I'm not sure, because I haven't encountered this issue for months. This should be already fixed in 0.9.4, but now it should be already fine with 1.19.2-2.1.
